"""THE CONTRACT, for agents that are trained instead of written.

A hand-written driver answers one question: *what do I do now?* A learned
driver answers three, and they are the three you actually compete on:

    features(obs) -> vector    what does the network get to see?
    reward(step)  -> float     what are we paying it to do?
    train = {...}              how long, how big, how greedy?

Everything else - the physics, the sensors, the scoring - is identical for
everyone, exactly as before. `Agent` subclasses `Driver`, so a trained
agent is a perfectly ordinary driver: play.py and evaluate.py neither know
nor care that a neural network is steering.

Do not edit this file. Edit drivers/my_driver.py.
"""

import math
import os
from dataclasses import dataclass

import numpy as np

from .driver_api import Control, Driver
from .policy import Policy


@dataclass
class StepInfo:
    """One environment step, handed to `reward()`.

    An env step is `action_repeat` physics ticks long, so `dt` is not
    necessarily 1/60 and `ds` is the whole distance covered in that window.
    """
    obs: object                 # Observation the action was chosen from
    next_obs: object            # Observation after the step
    control: Control            # what was actually applied
    prev_control: Control       # what was applied the step before
    ds: float = 0.0             # metres of centreline progress gained
    dt: float = 0.0             # seconds elapsed
    off_track_time: float = 0.0  # seconds of this step spent in the dirt
    wall_hit: bool = False      # ended up in the scenery: hit the edge of
                                # the run-off, or stayed off track too long
    collision: bool = False     # touched another car
    stalled: bool = False       # sat still / went backwards long enough to quit
    lap_done: bool = False      # crossed the line during this step
    terminal: bool = False      # the episode ends here (crash or stall)


class Agent(Driver):
    """Subclass this to enter a *trained* driver.

    The three things worth tuning are marked YOURS below. Everything else
    has a working default, so an untouched subclass trains into a
    respectable car.
    """

    name = "unnamed-agent"

    # ---- YOURS: the network ------------------------------------------------
    hidden = (64, 64)           # layer sizes of the actor and the critic
    action_repeat = 2           # physics ticks per decision (60 Hz / this)

    # ---- YOURS: the reward weights ----------------------------------------
    w_progress = 1.0            # per metre of track gained. The real goal.
    w_offtrack = 6.0            # per second in the dirt
    w_slip = 1.5                # per second of sliding past the grip limit
    w_jerk = 0.05               # per unit of steering wobble, keeps it smooth
    w_crash = 20.0              # one-off, for ending the episode in a wall
    w_contact = 1.0             # one-off, for banging into another car

    # ---- YOURS: the training run ------------------------------------------
    train = {
        "algo": "ppo",          # "ppo" (gradients) or "es" (evolution)
        "iterations": 300,
        "horizon": 600,         # env steps before an episode is cut short
        "steps_per_iter": 4096,  # PPO: experience gathered per iteration
        # 0.995 at 30 decisions/s is a 6-second memory. Shorter than about
        # five seconds and the agent cannot see the hairpin coming soon
        # enough to be paid for lifting off: it brakes late, every lap.
        "gamma": 0.995,
        "lam": 0.95,
        "clip": 0.2,
        "epochs": 10,
        "minibatch": 256,
        "lr": 3e-4,
        "vf_lr": 1e-3,
        "entropy": 0.003,
        "init_std": 0.4,
        # evolution only ("es", "cem", "ga")
        "population": 32,       # candidates per generation
        "elite": 8,             # how many of them survive it
        "es_episodes": 3,       # episodes each candidate is scored over
        "sigma": 0.05,          # es/cem: how far candidates sit from centre
        "es_lr": 0.02,          # es: step size towards the good ones
        "mutation_rate": 0.12,  # ga: fraction of a child's weights nudged
        "mutation_sigma": 0.06, # ga: how hard they are nudged
        "mutation_decay": 0.999,  # ga: settle down as the population improves
        "tournament": 3,        # ga: candidates per parent contest
    }

    # ---- set for you before the first drive() -----------------------------
    checkpoint = None           # defaults to runs/<module name>/best.npz
    policy = None
    trained = False

    # ======================================================== YOURS: seeing
    def features(self, obs):
        """Turn an Observation into the vector the network sees.

        Feed it too little and it cannot see the corner coming. Feed it too
        much and it takes ten times as long to learn. The default below is
        the honest minimum: where am I on the road, how fast, what is
        coming, and is anyone in the way.

        The one non-obvious entry is `over` - speed squared times curvature
        over the grip limit. Above 1.0 means the corner at that preview
        point cannot be taken at the current speed. That single number is
        the braking physics from the README, handed over for free; without
        it the agent has to learn to square a number by itself, and it
        will, slowly.
        """
        v = obs.speed
        half = max(obs.track_width * 0.5, 1.0)

        f = [
            v / 30.0,
            obs.lateral / half,
            obs.heading_error,
            obs.curvature * 40.0,
            obs.yaw_rate,
            obs.steer,
            min(obs.slip, 3.0),
            0.0 if obs.on_track else 1.0,
        ]

        for (fwd, left, _w, k) in obs.preview:
            f.append(math.atan2(left, max(fwd, 1.0)))      # which way it bends
            f.append(k * 40.0)                             # how hard
            over = v * v * abs(k) / self.mu_g              # >1 = too fast for it
            f.append(min(over, 4.0))

        for r in obs.rays:
            f.append(r / obs.ray_max)

        f.extend(self.traffic_features(obs))
        return np.asarray(f, dtype=np.float32)

    def traffic_features(self, obs):
        """Nearest car ahead and nearest behind, or "nobody there"."""
        ahead = behind = None
        for o in obs.opponents:
            if o.forward >= 0.0:
                if ahead is None or o.distance < ahead.distance:
                    ahead = o
            else:
                if behind is None or o.distance < behind.distance:
                    behind = o

        out = []
        for o in (ahead, behind):
            if o is None or o.distance > 60.0:
                out.extend((1.0, 0.0, 0.0))
            else:
                out.extend((o.forward / 60.0,
                            max(-1.0, min(1.0, o.left / 15.0)),
                            max(-1.0, min(1.0, o.rel_speed / 20.0))))
        return out

    # ======================================================= YOURS: wanting
    def reward(self, step):
        """What the agent is paid, per environment step.

        Progress along the track is the only term that says "go faster".
        Everything else is a fine for a way of going fast that does not
        survive three laps. Change these and you change the driver you get:
        drop `w_offtrack` and it will cut every corner; raise `w_jerk` too
        far and it will refuse to turn in.
        """
        r = self.w_progress * step.ds
        r -= self.w_offtrack * step.off_track_time
        r -= self.w_slip * max(0.0, step.next_obs.slip - 1.0) * step.dt
        r -= self.w_jerk * abs(step.control.steer - step.prev_control.steer)
        if step.collision:
            r -= self.w_contact
        if step.wall_hit or step.stalled:
            r -= self.w_crash
        return r

    # ==================================================== optional user hook
    def prepare(self, track_info, car_spec, race_info):
        """Extra precomputation, run once per race after setup().

        Anything you want available inside `features` - a racing line, a
        speed profile, a lookup table - build it here.
        """

    # =========================================================== the plumbing
    # Below this line is machinery. It is short enough to read, but you do
    # not have to change any of it to enter a competitive agent.

    def checkpoint_path(self):
        if self.checkpoint:
            return self.checkpoint
        return os.path.join("runs", self.module_name(), "best.npz")

    @classmethod
    def module_name(cls):
        return cls.__module__.rsplit(".", 1)[-1]

    def attach(self, policy):
        """Used by the trainer to drive with in-memory weights."""
        self.policy = policy
        self.trained = policy is not None
        return self

    def blank(self):
        """No weights, and do not go looking for any on disk.

        train.py needs an agent purely to ask how wide `features` is, before
        there is a network to put behind it.
        """
        self.policy = None
        self.trained = False
        self._skip_load = True
        return self

    def setup(self, track_info, car_spec, race_info):
        self.spec = car_spec
        self.track = track_info
        self.laps = race_info.get("laps", 3)
        self.mu_g = car_spec.grip_on * 9.81
        self.reset()

        if self.policy is None and not getattr(self, "_skip_load", False):
            path = self.checkpoint_path()
            if os.path.exists(path):
                self.policy = Policy.load(path)
                self.trained = True
            else:
                self.trained = False
        self.prepare(track_info, car_spec, race_info)

    def reset(self):
        self._tick = 0
        self._control = Control()
        self.last_obs = None      # what the current control was computed from

    def act(self, obs, rng=None, deterministic=True):
        """features -> network -> Control. No exploration noise by default."""
        feat = self.features(obs)
        if len(feat) != self.policy.obs_dim:
            raise ValueError(
                f"{self.name}: features() returns {len(feat)} numbers but "
                f"{self.checkpoint_path()} was trained on "
                f"{self.policy.obs_dim}. Retrain after changing features: "
                f"python train.py --driver {self.module_name()}")
        action, _mu, _logp = self.policy.act(feat, rng, deterministic)
        return self.to_control(action)

    def to_control(self, action):
        """Two numbers to three pedals.

        The second output is a single accelerator axis: positive is
        throttle, negative is brake. One axis instead of two makes it
        impossible to stand on both pedals at once, which is a mistake a
        fresh network otherwise makes for the first ten thousand steps.
        """
        steer = float(action[0])
        pedal = float(action[1])
        return Control(steer=steer,
                       throttle=max(pedal, 0.0),
                       brake=max(-pedal, 0.0))

    def drive(self, obs):
        if self.policy is None:
            return Control(0.0, 0.0, 1.0)      # untrained: park it
        if self._tick % max(int(self.action_repeat), 1) == 0:
            self._control = self.act(obs)
            self.last_obs = obs
        self._tick += 1
        return self._control

    # ------------------------------------------------------------- introspect
    def feature_dim(self, track_info, car_spec, race_info, probe_obs):
        """How wide is `features`? Asked once, before the net is built."""
        self.setup(track_info, car_spec, race_info)
        return int(len(self.features(probe_obs)))
