"""THE OBSERVATION, and the contract for hand-written drivers.

The simulator calls `drive(obs)` once per physics tick and applies whatever
you return. Nothing else about your driver matters, which is exactly why
two different authors' AIs can be compared fairly - and why a learned agent
and a hand-written one can race each other without either being favoured.

If you are training an agent rather than writing one, `racer/agent_api.py`
is your contract and this file is the field list: everything your
`features()` is allowed to look at is an attribute of `Observation` below.

Do not edit this file. Edit drivers/my_driver.py.
"""

import math
from dataclasses import dataclass, field
from typing import List, Tuple


@dataclass
class Control:
    """What you send back to the car every tick."""
    steer: float = 0.0      # -1 = full left, +1 = full right
    throttle: float = 0.0   # 0..1
    brake: float = 0.0      # 0..1

    def sanitised(self):
        def fix(v, lo, hi):
            try:
                v = float(v)
            except (TypeError, ValueError):
                return 0.0
            if math.isnan(v) or math.isinf(v):
                return 0.0
            return lo if v < lo else hi if v > hi else v

        return Control(fix(self.steer, -1.0, 1.0),
                       fix(self.throttle, 0.0, 1.0),
                       fix(self.brake, 0.0, 1.0))


@dataclass
class Opponent:
    """Another car, described in YOUR car's frame of reference."""
    index: int
    forward: float        # metres ahead of you (negative = behind)
    left: float           # metres to your left (negative = right)
    distance: float
    rel_speed: float      # their speed minus yours, m/s
    heading_diff: float   # their heading minus yours, radians (-pi..pi)
    gap_on_track: float   # their track progress minus yours, metres


@dataclass
class Observation:
    """Everything your driver is allowed to know this tick."""

    # --- time --------------------------------------------------------------
    time: float = 0.0             # seconds since the start
    dt: float = 1.0 / 60.0        # length of this tick

    # --- your car ----------------------------------------------------------
    speed: float = 0.0            # m/s (negative when reversing)
    heading: float = 0.0          # world radians
    yaw_rate: float = 0.0         # rad/s
    steer: float = 0.0            # the wheel angle actually applied last tick
    slip: float = 0.0             # 0 gripping .. 1 at the limit .. >1 sliding
    on_track: bool = True
    x: float = 0.0                # world position (mostly for debugging)
    y: float = 0.0

    # --- where you are on the circuit --------------------------------------
    progress: float = 0.0         # arc-length along the centreline, metres
    lap: int = 0
    lateral: float = 0.0          # + = left of centre, metres
    track_width: float = 20.0     # full width here
    dist_left_edge: float = 0.0   # metres to the left wall
    dist_right_edge: float = 0.0
    heading_error: float = 0.0    # your heading minus the track's, radians
    curvature: float = 0.0        # 1/m here; + = left bend

    # --- sensors: distance to the walls, car-relative angles ---------------
    ray_angles: Tuple[float, ...] = ()   # radians, 0 = straight ahead
    rays: Tuple[float, ...] = ()         # metres, capped at ray_max
    ray_max: float = 120.0

    # --- the road ahead ----------------------------------------------------
    # One entry per preview_distances[i]: (forward, left, width, curvature)
    # forward/left are in YOUR car's frame, metres.
    preview_distances: Tuple[float, ...] = ()
    preview: Tuple[Tuple[float, float, float, float], ...] = ()

    # --- traffic -----------------------------------------------------------
    opponents: List[Opponent] = field(default_factory=list)

    # --- race state --------------------------------------------------------
    position: int = 1             # 1 = leading
    total_laps: int = 3
    last_lap_time: float = 0.0
    best_lap_time: float = 0.0

    # -- convenience --------------------------------------------------------
    @property
    def speed_kmh(self):
        return self.speed * 3.6

    def ray(self, angle_deg):
        """Nearest ray to the given car-relative angle, in degrees."""
        if not self.rays:
            return self.ray_max
        target = math.radians(angle_deg)
        i = min(range(len(self.ray_angles)),
                key=lambda k: abs(self.ray_angles[k] - target))
        return self.rays[i]


class Driver:
    """Subclass this. `drive` is the only method you must write."""

    name = "unnamed"

    def setup(self, track_info, car_spec, race_info):
        """Called ONCE before the race. Do your heavy thinking here.

        track_info : dict from Track.info() - the full centreline, widths,
                     curvature and arc-length as numpy arrays. This is where
                     you would precompute a racing line.
        car_spec   : the CarSpec dataclass (mass, grip, engine force, ...)
        race_info  : {"laps": int, "n_cars": int, "your_index": int}

        Time spent here is not counted against your per-tick budget, but it
        is capped (see engine settings) so you cannot think for an hour.
        """

    def reset(self):
        """Called before every race in a tournament. Clear per-race state."""

    def drive(self, obs: Observation) -> Control:
        """Called every physics tick. Return a Control.

        Returning a plain tuple (steer, throttle, brake) also works.
        """
        raise NotImplementedError
