"""The iterations.

Two ways to search for the weights, both of which just repeat "try, score,
adjust" until the lap time stops falling:

  PPO  Proximal Policy Optimisation. Drives with a bit of random noise on
       the controls, works out which of those wobbles were followed by more
       reward than the critic expected, and nudges the network towards
       them. Sample-efficient, and the default. Roughly a hundred lines
       below, none of them mysterious.

  ES   Evolution Strategies. Forget gradients: fire off thirty-two slightly
       different copies of the driver, see which ones got round faster,
       and step in the direction of the winners. Needs more laps, but it
       never diverges, it does not care whether your reward is
       differentiable, and it parallelises across cores perfectly.

Both are generators. They yield a stats dict once per iteration and train.py
decides what to print, save and stop.

Do not edit this file. Edit drivers/my_driver.py.
"""

import importlib
import os
import sys
import time

import numpy as np

from .env import RacerEnv
from .policy import Adam, Policy, clip_grad_norm
from .race import Race
from .track import Track


# --------------------------------------------------------------------- setup

def load_agent_class(name):
    """The Driver class in drivers/<name>.py, without instantiating it."""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if root not in sys.path:
        sys.path.insert(0, root)
    module = importlib.import_module("drivers." + name)
    if not hasattr(module, "Driver"):
        raise AttributeError(f"drivers/{name}.py must define a class named Driver")
    return module.Driver


def make_env(track, agent_cls, policy, cfg, seed):
    agent = agent_cls().attach(policy)
    return RacerEnv(track, agent,
                    horizon=cfg["horizon"],
                    opponents=cfg.get("traffic", ()),
                    seed=seed)


# ----------------------------------------------------------------- rollouts

def rollout(env, policy, n_steps, rng):
    """Collect exactly n_steps of experience, resetting episodes as needed."""
    agent = env.agent
    D = policy.obs_dim
    feats = np.empty((n_steps, D), dtype=np.float32)
    nfeats = np.empty((n_steps, D), dtype=np.float32)
    acts = np.empty((n_steps, policy.act_dim), dtype=np.float32)
    rews = np.empty(n_steps, dtype=np.float32)
    nonterm = np.ones(n_steps, dtype=np.float32)
    boundary = np.zeros(n_steps, dtype=np.float32)

    ep_returns, ep_distance, ep_len, crashes = [], [], [], 0

    obs = env.obs if env.race is not None else env.reset()
    for t in range(n_steps):
        feat = agent.features(obs)
        action, _mu, _logp = policy.act(feat, rng)
        obs, r, done, info = env.step(action)

        feats[t] = feat
        acts[t] = action
        rews[t] = r
        nfeats[t] = agent.features(obs)
        nonterm[t] = 0.0 if done else 1.0

        if done or info["timeout"]:
            boundary[t] = 1.0
            ep_returns.append(env.episode_reward)
            ep_distance.append(env.episode_distance)
            ep_len.append(env.steps)
            crashes += 1 if info["crash"] or info["stalled"] else 0
            obs = env.reset()

    return {
        "feats": feats, "nfeats": nfeats, "acts": acts, "rews": rews,
        "nonterm": nonterm, "boundary": boundary,
        "ep_returns": ep_returns, "ep_distance": ep_distance,
        "ep_len": ep_len, "crashes": crashes,
    }


def gae(rews, values, next_values, nonterm, boundary, gamma, lam):
    """Generalised advantage estimation over a batch that may span episodes."""
    n = len(rews)
    adv = np.zeros(n, dtype=np.float32)
    run = 0.0
    for t in range(n - 1, -1, -1):
        delta = rews[t] + gamma * nonterm[t] * next_values[t] - values[t]
        run = delta + gamma * lam * nonterm[t] * (1.0 - boundary[t]) * run
        adv[t] = run
    return adv


# ---------------------------------------------------------------------- PPO

def ppo(track, agent_cls, policy, cfg, seed=0, workers=1):
    """Yields one stats dict per iteration. Runs until cfg['iterations']."""
    rng = np.random.default_rng(seed)
    pool = _Pool(track, agent_cls, cfg, workers, seed) if workers > 1 else None
    env = None if pool else make_env(track, agent_cls, policy, cfg, seed)

    actor_opt = Adam(policy.actor_size(), lr=cfg["lr"])
    critic_opt = Adam(policy.critic.size(), lr=cfg["vf_lr"])

    n = int(cfg["steps_per_iter"])
    gamma, lam, clip = cfg["gamma"], cfg["lam"], cfg["clip"]
    mb_size, epochs = int(cfg["minibatch"]), int(cfg["epochs"])
    ent_coef, target_kl = cfg["entropy"], cfg.get("target_kl", 0.02)
    total_steps = 0

    for it in range(1, int(cfg["iterations"]) + 1):
        t0 = time.perf_counter()

        if pool:
            batch = pool.rollout(policy, n)
        else:
            batch = rollout(env, policy, n, rng)
        collect = time.perf_counter() - t0
        # Split across workers, the batch rounds up; work with what arrived.
        m = len(batch["feats"])
        total_steps += m

        # Normalise with the SAME statistics the actor used while driving.
        fn = policy.norm(batch["feats"])
        nfn = policy.norm(batch["nfeats"])
        values = policy.value(fn)
        next_values = policy.value(nfn)

        adv = gae(batch["rews"], values, next_values,
                  batch["nonterm"], batch["boundary"], gamma, lam)
        returns = adv + values
        adv = (adv - adv.mean()) / (adv.std() + 1e-8)

        mu_old = policy.actor.forward(fn)
        logp_old = policy.logp_batch(mu_old, batch["acts"])

        idx = np.arange(m)
        kl = pl = vl = 0.0
        stopped = 0
        for epoch in range(epochs):
            rng.shuffle(idx)
            for start in range(0, m, mb_size):
                mb = idx[start:start + mb_size]
                pl, kl = _ppo_actor_step(policy, actor_opt, fn[mb],
                                         batch["acts"][mb], adv[mb],
                                         logp_old[mb], clip, ent_coef)
                vl = _critic_step(policy, critic_opt, fn[mb], returns[mb])
            if kl > 1.5 * target_kl:
                stopped = epochs - epoch - 1
                break

        policy.norm.update(batch["feats"])     # ready for the next iteration

        eps = max(len(batch["ep_returns"]), 1)
        yield {
            "iteration": it,
            "steps": total_steps,
            "return": float(np.mean(batch["ep_returns"])) if batch["ep_returns"] else 0.0,
            "distance": float(np.mean(batch["ep_distance"])) if batch["ep_distance"] else 0.0,
            "ep_len": float(np.mean(batch["ep_len"])) if batch["ep_len"] else 0.0,
            "episodes": len(batch["ep_returns"]),
            "crash_rate": batch["crashes"] / eps,
            "policy_loss": float(pl), "value_loss": float(vl), "kl": float(kl),
            "std": float(np.exp(policy.log_std).mean()),
            "early_stop": stopped,
            "collect_s": collect,
            "iter_s": time.perf_counter() - t0,
        }

    if pool:
        pool.close()


def _ppo_actor_step(policy, opt, fn, acts, adv, logp_old, clip, ent_coef):
    cache = []
    mu = policy.actor.forward(fn, cache)
    logp = policy.logp_batch(mu, acts)
    ratio = np.exp(np.clip(logp - logp_old, -20.0, 20.0)).astype(np.float32)

    unclipped = ratio * adv
    clipped = np.clip(ratio, 1.0 - clip, 1.0 + clip) * adv
    # The gradient flows through whichever branch the min() picked - and
    # also through the clipped branch while the ratio is still inside the
    # trust region, where clipping is the identity.
    inside = (ratio > 1.0 - clip) & (ratio < 1.0 + clip)
    flow = (unclipped <= clipped) | inside

    m = len(fn)
    dlogp = np.where(flow, -ratio * adv / m, 0.0).astype(np.float32)

    std = np.exp(policy.log_std)
    z = (acts - mu) / std
    dmu = (dlogp[:, None] * z / std).astype(np.float32)
    dlog_std = (dlogp[:, None] * (z ** 2 - 1.0)).sum(0) - ent_coef

    grads = policy.actor.backward(dmu, cache)
    flat = np.concatenate([policy.actor.flatten_grads(grads),
                           dlog_std.astype(np.float32)])
    flat, _ = clip_grad_norm(flat, 0.5)

    theta = opt.step(policy.get_actor_flat(), flat)
    policy.set_actor_flat(theta)
    policy.clip_std()

    loss = -float(np.mean(np.minimum(unclipped, clipped)))
    kl = float(np.mean(logp_old - logp))
    return loss, kl


def _critic_step(policy, opt, fn, returns):
    cache = []
    v = policy.critic.forward(fn, cache)[:, 0]
    diff = (v - returns).astype(np.float32)
    grads = policy.critic.backward((diff / len(fn))[:, None], cache)
    flat, _ = clip_grad_norm(policy.critic.flatten_grads(grads), 0.5)
    policy.set_critic_flat(opt.step(policy.get_critic_flat(), flat))
    return float(0.5 * np.mean(diff ** 2))


# ----------------------------------------------------------------------- ES

def centered_ranks(x):
    """Map fitnesses to evenly spaced ranks in [-0.5, 0.5].

    Rank instead of raw score, so one freak episode cannot drag the whole
    population after it.
    """
    order = np.argsort(x)
    ranks = np.empty(len(x), dtype=np.float32)
    ranks[order] = np.arange(len(x), dtype=np.float32)
    return ranks / max(len(x) - 1, 1) - 0.5


class EsOptimizer:
    """Ask for a population, say how each one did, get a better centre.

    Two rules, and the difference is worth knowing:

    "es"   every member votes. Each is scored, the scores are turned into
           ranks, and the centre slides towards the ones that did well and
           away from the ones that did badly. Nobody survives - the whole
           population is thrown away and resampled around the new centre.

    "cem"  only the best few survive. The new centre is literally the
           average of the elite, and everyone else is discarded. This is
           the one that matches what it looks like on screen: the cars that
           crashed contribute nothing, the ones that got furthest become
           the next generation.
    """

    def __init__(self, theta, cfg, rng):
        self.rule = self.name = "cem" if cfg.get("algo") == "cem" else "es"
        self.survivors = []          # nobody survives; see GaOptimizer
        self.rng = rng
        self.theta = np.asarray(theta, dtype=np.float32).copy()
        self.sigma = float(cfg["sigma"])
        self.pop = max(int(cfg["population"]) - int(cfg["population"]) % 2, 4)
        self.elite = max(int(cfg.get("elite", max(self.pop // 4, 2))), 2)
        self.opt = Adam(len(self.theta), lr=cfg["es_lr"])
        self.members = None
        self.noise = None

    def ask(self):
        """One generation of candidates, mirrored in pairs around the centre."""
        eps = self.rng.standard_normal(
            (self.pop // 2, len(self.theta))).astype(np.float32)
        self.noise = np.concatenate([eps, -eps], axis=0)
        self.members = self.theta[None, :] + self.sigma * self.noise
        return self.members

    def tell(self, fitness):
        fitness = np.asarray(fitness, dtype=np.float32)
        if self.rule == "cem":
            keep = np.argsort(fitness)[-self.elite:]
            self.theta = self.members[keep].mean(axis=0).astype(np.float32)
        else:
            ranks = centered_ranks(fitness)
            grad = -(self.noise.T @ ranks) / (self.pop * self.sigma)
            grad, _ = clip_grad_norm(grad.astype(np.float32), 1.0)
            self.theta = self.opt.step(self.theta, grad)
        return self.theta

    def describe(self):
        if self.rule == "cem":
            return f"top {self.elite} averaged into the next centre"
        return f"all {self.pop} vote, weighted by rank"


class GaOptimizer:
    """A population that breeds. The one people mean by "genetic algorithm".

    Unlike es and cem, an individual here is a whole driver in its own
    right, not a wobble around a shared centre. Each generation:

      1. everyone drives, everyone gets a score
      2. the best `elite` are copied into the next generation UNCHANGED -
         they survive as themselves, which is the part the other two do not
         do
      3. every remaining place is filled by a child: two parents are picked
         by tournament (grab three at random, keep the best), a coin is
         flipped per weight to decide which parent it comes from, and then
         a few weights are nudged at random

    That last nudge is the mutation, and it is the only source of anything
    genuinely new. Too little and the population converges to one driver and
    stops improving; too much and good parents produce broken children.
    `mutation_rate` is what fraction of weights get touched, `mutation_sigma`
    is how hard.
    """

    name = "ga"

    def __init__(self, theta, cfg, rng, population=None):
        self.rng = rng
        n = len(theta)
        self.pop = max(int(cfg["population"]), 4)
        self.elite = int(np.clip(int(cfg.get("elite", 8)), 1, self.pop - 1))
        self.mutation_rate = float(cfg.get("mutation_rate", 0.12))
        self.sigma = float(cfg.get("mutation_sigma", 0.06))
        self.decay = float(cfg.get("mutation_decay", 0.999))
        self.floor = float(cfg.get("mutation_floor", 0.01))
        self.tournament = max(int(cfg.get("tournament", 3)), 2)

        if population is None:
            population = (np.asarray(theta, dtype=np.float32)[None, :]
                          + 0.3 * rng.standard_normal((self.pop, n)))
        self.members = np.asarray(population, dtype=np.float32).copy()
        self.members[0] = theta            # the driver you started from
        self.theta = self.members[0].copy()
        self.survivors = []

    def ask(self):
        return self.members

    def tell(self, fitness):
        fitness = np.asarray(fitness, dtype=np.float32)
        order = np.argsort(fitness)[::-1]               # best first

        nxt = np.empty_like(self.members)
        nxt[:self.elite] = self.members[order[:self.elite]]      # survivors
        for i in range(self.elite, self.pop):
            a = self.members[self._pick(fitness)]
            b = self.members[self._pick(fitness)]
            nxt[i] = self._mutate(self._cross(a, b))

        self.members = nxt
        self.survivors = list(range(self.elite))
        self.theta = self.members[0].copy()             # the champion
        self.sigma = max(self.sigma * self.decay, self.floor)
        return self.theta

    def _pick(self, fitness):
        """Tournament selection: a few at random, the best of them breeds."""
        picks = self.rng.integers(0, self.pop, size=self.tournament)
        return int(picks[int(np.argmax(fitness[picks]))])

    def _cross(self, a, b):
        take_a = self.rng.random(len(a)) < 0.5
        return np.where(take_a, a, b).astype(np.float32)

    def _mutate(self, child):
        hit = self.rng.random(len(child)) < self.mutation_rate
        noise = self.rng.standard_normal(len(child)).astype(np.float32)
        return (child + hit * self.sigma * noise).astype(np.float32)

    def describe(self):
        return (f"top {self.elite} survive, {self.pop - self.elite} bred "
                f"(mutation {self.sigma:.3f})")


def random_population(obs_dim, act_dim, hidden, n, seed, out_gain=0.5):
    """n independently initialised drivers - generation one of a GA.

    Perturbing a single network gives you thirty-two near-identical cars.
    Independent draws give you a crowd that already behaves differently,
    which is the only thing selection can work with on the first generation.
    """
    return np.stack([
        Policy(obs_dim, act_dim, hidden, seed=seed + 977 * (i + 1),
               out_gain=out_gain).actor.get_flat()
        for i in range(n)
    ]).astype(np.float32)


def make_optimizer(policy, cfg, rng, seed=0):
    """es / cem / ga, all behind the same ask() and tell()."""
    theta = policy.actor.get_flat()
    if cfg.get("algo") == "ga":
        pop = max(int(cfg["population"]), 4)
        start = random_population(policy.obs_dim, policy.act_dim,
                                  policy.hidden, pop, seed)
        return GaOptimizer(theta, cfg, rng, population=start)
    return EsOptimizer(theta, cfg, rng)


def evolve(track, agent_cls, policy, cfg, seed=0, workers=1):
    rng = np.random.default_rng(seed)
    episodes = int(cfg["es_episodes"])

    pool = _Pool(track, agent_cls, cfg, workers, seed) if workers > 1 else None
    env = None if pool else make_env(track, agent_cls, policy, cfg, seed)

    # ES never updates the feature statistics mid-run (the workers would all
    # drift apart), so fit them once, up front, from the newborn policy.
    warmup_normalizer(env or make_env(track, agent_cls, policy, cfg, seed + 99),
                      policy, 3000, rng)
    if pool:
        pool.sync_norm(policy)

    opt = make_optimizer(policy, cfg, rng, seed)
    total_steps = 0

    for it in range(1, int(cfg["iterations"]) + 1):
        t0 = time.perf_counter()
        thetas = opt.ask()

        # Everyone in the population drives the SAME episodes this iteration,
        # so a lucky starting point cannot decide the winner.
        seeds = rng.integers(0, 2 ** 31 - 1, size=episodes).tolist()

        if pool:
            fitness, dist, steps = pool.evaluate(thetas, seeds)
        else:
            fitness, dist, steps = _evaluate_local(env, policy, thetas, seeds)
        total_steps += steps

        policy.actor.set_flat(opt.tell(fitness))

        yield {
            "iteration": it,
            "steps": total_steps,
            "return": float(fitness.mean()),
            "best_return": float(fitness.max()),
            "distance": float(dist.mean()),
            "episodes": opt.pop * episodes,
            "crash_rate": 0.0,
            "std": float(opt.sigma),
            "iter_s": time.perf_counter() - t0,
            "collect_s": time.perf_counter() - t0,
        }

    if pool:
        pool.close()


def _evaluate_local(env, policy, thetas, seeds):
    base = policy.actor.get_flat()
    fitness = np.zeros(len(thetas), dtype=np.float32)
    dist = np.zeros(len(thetas), dtype=np.float32)
    steps = 0
    for i, th in enumerate(thetas):
        policy.actor.set_flat(th)
        for s in seeds:
            r, d = env.rollout_episode(policy, deterministic=True, seed=int(s))
            fitness[i] += r / len(seeds)
            dist[i] += d / len(seeds)
            steps += env.steps
    policy.actor.set_flat(base)
    return fitness, dist, steps


def warmup_normalizer(env, policy, n, rng):
    """Fit the feature statistics before anyone learns anything."""
    feats = []
    obs = env.reset()
    while len(feats) < n:
        f = env.agent.features(obs)
        feats.append(f)
        a, _, _ = policy.act(f, rng)
        obs, _r, done, info = env.step(a)
        if done or info["timeout"]:
            obs = env.reset()
    policy.norm.update(np.asarray(feats, dtype=np.float32))


# ------------------------------------------------------------------ scoring

def lap_eval(track, agent_cls, policy, laps=2, time_limit=180.0):
    """A proper time trial with the current weights. Slow but honest."""
    agent = agent_cls().attach(policy)
    race = Race(track, [(agent.name, agent)], laps=laps, collisions=False,
                time_limit=time_limit)
    start = race.entrants[0].progress
    row = race.run()[0]
    row["distance"] = row["progress"] - start      # metres actually covered
    return row


# ------------------------------------------------------------- worker pool

_W = {}


def _worker_init(track_path, driver_name, cfg, base_seed, counter):
    import numpy as _np
    _np.seterr(all="ignore")
    # Pool hands every worker the same arguments, so they number themselves
    # off a shared counter. Rank only decides the seed, but two workers
    # rolling out identical episodes would waste half the machine.
    with counter.get_lock():
        rank = counter.value
        counter.value += 1
    track = Track.load(track_path)
    agent_cls = load_agent_class(driver_name)
    policy = Policy(int(cfg["obs_dim"]), 2, tuple(cfg["hidden"]),
                    init_std=cfg["init_std"], seed=base_seed)
    env = make_env(track, agent_cls, policy, cfg, base_seed + 1000 * (rank + 1))
    _W["env"] = env
    _W["policy"] = policy
    _W["rng"] = _np.random.default_rng(base_seed + 7919 * (rank + 1))


def _worker_rollout(payload):
    actor, mean, var, count, n = payload
    p = _W["policy"]
    p.set_actor_flat(actor)
    p.norm.load(mean, var, count)
    return rollout(_W["env"], p, n, _W["rng"])


def _worker_norm(payload):
    mean, var, count = payload
    _W["policy"].norm.load(mean, var, count)
    return True


def _worker_es(payload):
    thetas, seeds = payload
    p = _W["policy"]
    env = _W["env"]
    fit = np.zeros(len(thetas), dtype=np.float32)
    dist = np.zeros(len(thetas), dtype=np.float32)
    steps = 0
    for i, th in enumerate(thetas):
        p.actor.set_flat(th)
        for s in seeds:
            r, d = env.rollout_episode(p, deterministic=True, seed=int(s))
            fit[i] += r / len(seeds)
            dist[i] += d / len(seeds)
            steps += env.steps
    return fit, dist, steps


class _Pool:
    """One process per core, each holding a warm environment of its own."""

    def __init__(self, track, agent_cls, cfg, workers, seed):
        import multiprocessing as mp
        self.n = int(workers)
        ctx = mp.get_context("spawn")
        counter = ctx.Value("i", 0)
        self.pool = ctx.Pool(
            self.n, initializer=_worker_init,
            initargs=(cfg["track_path"], cfg["driver"], cfg, seed, counter))

    def rollout(self, policy, n_steps):
        mean, var, count = policy.norm.state()
        per = max(-(-n_steps // self.n), 1)      # round up, never short
        payload = (policy.get_actor_flat(), mean, var, count, per)
        parts = self.pool.map(_worker_rollout, [payload] * self.n, chunksize=1)
        return _merge(parts)

    def sync_norm(self, policy):
        mean, var, count = policy.norm.state()
        self.pool.map(_worker_norm, [(mean, var, count)] * self.n, chunksize=1)

    def evaluate(self, thetas, seeds):
        chunks = np.array_split(thetas, self.n)
        out = self.pool.map(_worker_es, [(c, seeds) for c in chunks], chunksize=1)
        fit = np.concatenate([o[0] for o in out])
        dist = np.concatenate([o[1] for o in out])
        return fit, dist, sum(o[2] for o in out)

    def close(self):
        self.pool.close()
        self.pool.join()


def _merge(parts):
    out = {}
    for key in ("feats", "nfeats", "acts", "rews", "nonterm", "boundary"):
        out[key] = np.concatenate([p[key] for p in parts], axis=0)
    for key in ("ep_returns", "ep_distance", "ep_len"):
        out[key] = [v for p in parts for v in p[key]]
    out["crashes"] = sum(p["crashes"] for p in parts)
    return out
