"""The brain: a small neural network, written in plain numpy.

Two nets and a noise level, which is all any policy-gradient method needs:

    actor   features -> tanh -> tanh -> 2 numbers in (-1, 1)
    critic  features -> tanh -> tanh -> 1 number (expected future reward)
    log_std the exploration noise, learned alongside the actor

There is no autograd here. `backward()` is thirty lines of chain rule,
which is worth reading once: it is the entire difference between "the
network guessed" and "the network learned".

Everything is float32 and flat-vector addressable (`get_flat`/`set_flat`),
because evolution strategies wants to perturb the whole parameter vector
at once and Adam is simplest in flat space.

Do not edit this file. Edit drivers/my_driver.py.
"""

import os

import numpy as np

LOG_STD_MIN = -3.5     # sigma ~ 0.03: essentially deterministic
LOG_STD_MAX = 0.3      # sigma ~ 1.35: flailing


class Normalizer:
    """Running mean/variance of the features, updated in batches.

    Neural nets learn badly when one input is measured in radians (~0.1)
    and the next in metres (~120). This rescales every feature to roughly
    zero mean and unit variance. The statistics are saved with the
    checkpoint and FROZEN at race time, so a trained driver sees exactly
    the numbers it was trained on.
    """

    # Below this observed variance a feature is treated as constant and is
    # NOT rescaled. Dividing by the standard deviation of something that
    # never moved multiplies the first real value you ever see by tens of
    # thousands: an agent trained alone would meet its first opponent, take
    # a +10 spike on every traffic input, and drive straight off the road.
    # No evidence of scale means leave the scale alone - which is safe,
    # because features are supposed to arrive at roughly unit size anyway.
    CONSTANT_VAR = 1e-4

    def __init__(self, dim):
        self.mean = np.zeros(dim, dtype=np.float64)
        self.var = np.ones(dim, dtype=np.float64)
        self.count = 1e-4
        self._rescale()

    def update(self, x):
        x = np.asarray(x, dtype=np.float64)
        if x.ndim == 1:
            x = x[None, :]
        if len(x) == 0:
            return
        bm, bv, bn = x.mean(0), x.var(0), len(x)

        delta = bm - self.mean
        tot = self.count + bn
        self.mean += delta * bn / tot
        m_a = self.var * self.count
        m_b = bv * bn
        self.var = (m_a + m_b + delta ** 2 * self.count * bn / tot) / tot
        self.count = tot
        self._rescale()

    def _rescale(self):
        scale = np.sqrt(self.var + 1e-8)
        scale[self.var < self.CONSTANT_VAR] = 1.0
        self._mean32 = self.mean.astype(np.float32)
        self._scale32 = scale.astype(np.float32)

    def __call__(self, x):
        z = (np.asarray(x, dtype=np.float32) - self._mean32) / self._scale32
        return np.clip(z, -10.0, 10.0)

    def state(self):
        return self.mean.copy(), self.var.copy(), np.array([self.count])

    def load(self, mean, var, count):
        self.mean = np.asarray(mean, dtype=np.float64).copy()
        self.var = np.asarray(var, dtype=np.float64).copy()
        self.count = float(np.asarray(count).ravel()[0])
        self._rescale()


class MLP:
    """Fully connected net, tanh everywhere except (optionally) the output."""

    def __init__(self, sizes, rng, out_gain=0.01, tanh_out=False):
        self.sizes = list(sizes)
        self.tanh_out = tanh_out
        self.W, self.b = [], []
        n = len(sizes) - 1
        for i in range(n):
            # Scaled init: gain sqrt(2) in the body keeps the signal alive
            # through tanh; a tiny final gain makes the freshly born policy
            # output near zero, i.e. "coast", instead of thrashing.
            gain = np.sqrt(2.0) if i < n - 1 else out_gain
            w = rng.standard_normal((sizes[i], sizes[i + 1])).astype(np.float32)
            w *= gain / np.sqrt(sizes[i])
            self.W.append(w)
            self.b.append(np.zeros(sizes[i + 1], dtype=np.float32))

    # ------------------------------------------------------------ inference
    def forward(self, x, cache=None):
        a = np.asarray(x, dtype=np.float32)
        if a.ndim == 1:
            a = a[None, :]
        if cache is not None:
            cache.append(a)
        last = len(self.W) - 1
        for i, (W, b) in enumerate(zip(self.W, self.b)):
            a = a @ W + b
            if i < last or self.tanh_out:
                a = np.tanh(a)
            if cache is not None:
                cache.append(a)
        return a

    # ------------------------------------------------------------- learning
    def backward(self, dout, cache):
        """Chain rule. `cache` is [input, act1, act2, ..., output]."""
        grads = []
        d = dout
        last = len(self.W) - 1
        for i in range(last, -1, -1):
            if i < last or self.tanh_out:
                d = d * (1.0 - cache[i + 1] ** 2)      # derivative of tanh
            grads.append((cache[i].T @ d, d.sum(0)))
            d = d @ self.W[i].T
        grads.reverse()
        return grads

    # ------------------------------------------------------- flat parameters
    def size(self):
        return sum(w.size for w in self.W) + sum(b.size for b in self.b)

    def get_flat(self):
        out = []
        for W, b in zip(self.W, self.b):
            out.append(W.ravel())
            out.append(b.ravel())
        return np.concatenate(out)

    def set_flat(self, v, i=0):
        for k in range(len(self.W)):
            n = self.W[k].size
            self.W[k] = v[i:i + n].reshape(self.W[k].shape).astype(np.float32)
            i += n
            n = self.b[k].size
            self.b[k] = v[i:i + n].astype(np.float32)
            i += n
        return i

    def flatten_grads(self, grads):
        out = []
        for dW, db in grads:
            out.append(dW.ravel())
            out.append(db.ravel())
        return np.concatenate(out).astype(np.float32)


class Policy:
    """Actor + critic + exploration noise. The thing training produces."""

    def __init__(self, obs_dim, act_dim=2, hidden=(64, 64), init_std=0.4,
                 seed=0, out_gain=0.01):
        # out_gain is how loud a newborn network is. Gradient methods want
        # it near zero, so the first policy coasts instead of thrashing and
        # the updates decide what it does. A genetic algorithm wants the
        # opposite: if every car in generation one sits still, they all
        # score the same and selection has nothing to choose between.
        rng = np.random.default_rng(seed)
        self.obs_dim, self.act_dim, self.hidden = obs_dim, act_dim, tuple(hidden)
        self.actor = MLP([obs_dim, *hidden, act_dim], rng,
                         out_gain=out_gain, tanh_out=True)
        self.critic = MLP([obs_dim, *hidden, 1], rng, out_gain=1.0)
        self.log_std = np.full(act_dim, np.log(init_std), dtype=np.float32)
        self.norm = Normalizer(obs_dim)
        self.meta = {}

    # ------------------------------------------------------------ inference
    def act(self, feat, rng=None, deterministic=False):
        """feat is RAW features; normalisation happens in here."""
        mu = self.actor.forward(self.norm(feat))[0]
        if deterministic or rng is None:
            return np.clip(mu, -1.0, 1.0), mu, 0.0
        std = np.exp(self.log_std)
        a = mu + std * rng.standard_normal(self.act_dim).astype(np.float32)
        return np.clip(a, -1.0, 1.0), mu, float(self.logp_batch(mu[None], a[None])[0])

    def value(self, feat_norm):
        return self.critic.forward(feat_norm)[:, 0]

    def logp_batch(self, mu, a):
        std = np.exp(self.log_std)
        z = (a - mu) / std
        return (-0.5 * np.sum(z ** 2, axis=1) - np.sum(self.log_std)
                - 0.5 * self.act_dim * np.log(2 * np.pi))

    def entropy(self):
        return float(np.sum(self.log_std) + 0.5 * self.act_dim *
                     np.log(2 * np.pi * np.e))

    def clip_std(self):
        self.log_std = np.clip(self.log_std, LOG_STD_MIN, LOG_STD_MAX)

    # ------------------------------------------------- flat parameter access
    def actor_size(self):
        return self.actor.size() + self.act_dim

    def get_actor_flat(self):
        return np.concatenate([self.actor.get_flat(), self.log_std])

    def set_actor_flat(self, v):
        i = self.actor.set_flat(v)
        self.log_std = v[i:i + self.act_dim].astype(np.float32)

    def get_critic_flat(self):
        return self.critic.get_flat()

    def set_critic_flat(self, v):
        self.critic.set_flat(v)

    # --------------------------------------------------------------- saving
    def save(self, path, meta=None):
        folder = os.path.dirname(os.path.abspath(path))
        if folder:
            os.makedirs(folder, exist_ok=True)
        mean, var, count = self.norm.state()
        blob = {
            "actor": self.get_actor_flat(),
            "critic": self.get_critic_flat(),
            "obs_dim": np.array([self.obs_dim]),
            "act_dim": np.array([self.act_dim]),
            "hidden": np.array(self.hidden),
            "norm_mean": mean, "norm_var": var, "norm_count": count,
        }
        for k, v in (meta or {}).items():
            blob["meta_" + k] = np.array(v)

        # Write beside the target and rename into place. A live viewer polls
        # this file while training writes it, and half a checkpoint loads as
        # a corrupt archive rather than as an error you can understand.
        tmp = path[:-4] + ".part.npz" if path.endswith(".npz") else path + ".part.npz"
        np.savez(tmp, **blob)
        os.replace(tmp, path if path.endswith(".npz") else path + ".npz")

    @classmethod
    def load(cls, path):
        d = np.load(path, allow_pickle=False)
        p = cls(int(d["obs_dim"][0]), int(d["act_dim"][0]),
                tuple(int(h) for h in d["hidden"]))
        p.set_actor_flat(d["actor"])
        p.set_critic_flat(d["critic"])
        p.norm.load(d["norm_mean"], d["norm_var"], d["norm_count"])
        p.meta = {k[5:]: d[k] for k in d.files if k.startswith("meta_")}
        return p


class Adam:
    """Plain Adam over a flat parameter vector."""

    def __init__(self, n, lr=3e-4, b1=0.9, b2=0.999, eps=1e-8):
        self.lr, self.b1, self.b2, self.eps = lr, b1, b2, eps
        self.m = np.zeros(n, dtype=np.float32)
        self.v = np.zeros(n, dtype=np.float32)
        self.t = 0

    def step(self, theta, grad):
        """Returns theta moved DOWN the gradient."""
        self.t += 1
        self.m = self.b1 * self.m + (1 - self.b1) * grad
        self.v = self.b2 * self.v + (1 - self.b2) * grad ** 2
        mh = self.m / (1 - self.b1 ** self.t)
        vh = self.v / (1 - self.b2 ** self.t)
        return (theta - self.lr * mh / (np.sqrt(vh) + self.eps)).astype(np.float32)


def clip_grad_norm(grad, max_norm):
    n = float(np.linalg.norm(grad))
    if n > max_norm and n > 0:
        grad = grad * (max_norm / n)
    return grad.astype(np.float32), n
